# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284ba3a00124c08205709b0b7aad8ad3e4543f7390431b6f2b450d67e7c18f02e590da6bab0e6c80e5ce81d932d2b79d597ae7f42cb68f9cf2cfb54fdaacab7f

test:
  secret_key_base: 969da49c7c13c32a2544501755a6e97ae7f386627d7130d11421d42297cd54efd1128d9fe81b66a401f02c69e647cb26d2baae9dc7850d147aca1dcaca99cdeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
